_core:
  default_config_hash: koZKG6ZJXEycSayM13ngD-P7IOXAlGoaJR_CyrYxL84
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  logo: true
  name: true
  node_user_picture: 1
  slogan: true
facebook_url: 'https://www.facebook.com/srirama.a.315/'
twitter_url: 'https://twitter.com/zymphonies'
linkedin_url: 'https://www.linkedin.com/in/sriram19'
instagram_url: 'https://www.facebook.com/srirama.a.315/'
rss_url: rss.xml
show_social_icon: 1
show_credit_link: 0
show_slideshow: 1
slide_title_1: 'The Easiest Way to Get suitable Property'
slide_description_1: 'Find Flats, Apartments & Real Estate'
slide_url_1: '#'
slide_image_path_1: /images/slider/slide_01.jpg
logo:
  use_default: 1
favicon:
  use_default: 1
slide_image_path1: {  }
