_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 23ff6891-4652-420a-b970-687fbbc55e07
name: 'Learning Experience'
mail: sriramanandan19@gmail.com
slogan: '  Learning new things'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
